sudo: required
dist: trusty

language: haxe

# haxe versions : http://haxe.org/website-content/downloads/versions.json

haxe:
- "3.2.1"
- "3.3.0-rc.1"
- "3.4.0-rc.1"
- development

install:
- haxelib install travix 
- haxelib git haxe-js-kit https://github.com/clemos/haxe-js-kit.git c43587462fb7c470257a49c29bb1a923c0ca5f14  --always
- haxelib dev haxesandbox .

script:
- haxelib run travix js
- cat bin/js/tests.js

notifications:
  email:
    recipients:
    - laurent@geturl.net